name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack Elmah.Io.Extensions.Logging
      run: dotnet pack --configuration Release src/Elmah.Io.Extensions.Logging/Elmah.Io.Extensions.Logging.csproj /p:Version=3.9.${{ github.run_number }}-pre
    - name: Pack Elmah.Io.AspNetCore.ExtensionsLogging
      run: dotnet pack --configuration Release src/Elmah.Io.AspNetCore.ExtensionsLogging/Elmah.Io.AspNetCore.ExtensionsLogging.csproj /p:Version=3.9.${{ github.run_number }}-pre
